-- Insert 150 words into abcd table

INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('applause', '/əˈplɔːz/', '鼓掌、喝彩；称赞(u)', '{"example":"The audience gave loud applause.","example_translation":"观众热烈鼓掌。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('pinch', '/pɪntʃ/', '捏、掐(c, vt)；一撮、少量(c)；困苦(u)；逮捕(vt)；(穿的鞋等)夹痛(v)', '{"example":"She pinched my arm gently.","example_translation":"她轻轻掐了我的胳膊。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('belly', '/ˈbeli/', '腹部；(物体的)圆形或凸起部分(c)；(使)(帆)鼓起(v)', '{"example":"The baby patted its soft belly.","example_translation":"婴儿拍了拍它柔软的腹部。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('stomach', '/ˈstʌmək/', '胃(部)(c)；胃口(n)；忍受(vt)', '{"example":"I feel my stomach ache now","example_translation":"我现在感觉胃痛\n\n例句: The smell kills my stomach\n翻译: 这气味让我倒胃口\n\n例句: I can''''t stomach his lies\n翻译: 我无法忍受他的谎言"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('bowel', '/ˈbaʊəl/', '肠(c, usually pl)；内部最深处(pl, the bowels of sth)', '{"example":"She cleansed her bowels daily.","example_translation":"她每天清洗肠道。\n\n例句: We explored the bowels of the cave.\n翻译: 我们探索了洞穴的内部最深处。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('waist', '/weɪst/', '(人或衣服的)腰、腰部(c)', '{"example":"She measured her waist today.","example_translation":"她今天量了自己的腰围。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('hip', '/hɪp/', '髋、臀部(c)', '{"example":"She hurt her hip yesterday.","example_translation":"她昨天伤到了髋部。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('appendix', '/əˈpendɪks/', '阑尾；(书、文件的)附录；附属物(c)', '{"example":"The doctor removed his appendix.","example_translation":"医生切除了他的阑尾。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('leg', '/leɡ/', '(人、裤子、桌子等的)腿(c)；跑(vi)', '{"example":"She crossed her legs gently.","example_translation":"她轻轻交叉双腿。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('thigh', '/θaɪ/', '大腿；(供食用的禽类的)腿(c)', '{"example":"She rubbed her sore thigh gently.","example_translation":"她轻轻揉了揉酸痛的大腿。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('knee', '/niː/', '膝盖、膝关节；(裤子的)膝部(c)', '{"example":"She hit her knee on the table.","example_translation":"她的膝盖撞到了桌子上。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('heel', '/hiːl/', '(脚、鞋、袜等的)后跟(c)；倾斜(phr v, ~ over)', '{"example":"She repaired her shoe''''s heel.","example_translation":"她修好了她鞋子的后跟。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('remains', '/rɪˈmeɪnz/', '遗体；遗迹；剩余物(如剩饭剩菜)(plural)', '{"example":"The archaeologists found ancient remains.","example_translation":"考古学家发现了古老遗迹。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('skeleton', '/ˈskelɪtn/', '骨架、骨骼；(建筑的)骨架(c)；纲要(c, usually sing)；骨骼的', '{"example":"The old building''''s skeleton remains strong.","example_translation":"这座旧建筑的骨架依然坚固。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('joint', '/dʒɔɪnt/', '关节；接头、接缝、结合处(c)；(用接头等)结合(vt)；共同的、联合的(only before noun)', '{"example":"We wrap the joint with tape.","example_translation":"我们用胶带包裹这个接头。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('skin', '/skɪn/', '皮肤、(动物、果蔬的)皮(n)；剥去…的皮(vt)', '{"example":"She applies cream to her skin.","example_translation":"她往皮肤上涂面霜。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('artery', '/ˈɑːrtəri/', '动脉；(河流、公路等的)干线(c)', '{"example":"A blocked artery causes health risks.","example_translation":"一条堵塞的动脉会带来健康风险。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('vein', '/veɪn/', '静脉；翅脉、叶脉；(木头、石头等的)纹理(c)', '{"example":"The doctor injected medicine into her vein","example_translation":"医生将药物注射进她的静脉"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('nerve', '/nɜːrv/', '神经(c)；神经质(pl)；勇气(u)；鼓足勇气(vt, ~ yourself to do sth)', '{"example":"She felt a nerve twitch in her leg","example_translation":"她感到腿上的一根神经在抽搐\n\n例句: His nerves calmed after the test\n翻译: 考试后他的神经质症状缓解了\n\n例句: He had the nerve to speak up\n翻译: 他有勇气站出来说话\n\n例句: She nerved herself to enter the room\n翻译: 她鼓足勇气走进房间"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('cell', '/sel/', '细胞；电池；单人牢房(c)', '{"example":"A plant cell contains chloroplasts.","example_translation":"植物细胞含有叶绿体。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('attribute', '/əˈtrɪbjuːt/', '(人或物的)属性、特征(c)；把…归因于(vt, ~ sth to sb/sth)', '{"example":"She attributes her success to hard work","example_translation":"她把成功归因于努力工作"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('characteristic', '/ˌkærəktəˈrɪstɪk/', '(人或物的)特征、特色(c, usually pl)；特有的、典型的', '{"example":"Her smile shows her sweet characteristic.","example_translation":"她的微笑展现了她甜美的特征。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('feature', '/ˈfiːtʃər/', '(地方或事物的)特征、特色；特写；故事片(c)；面貌(c, usually pl)；以…为特色(vt, ~ sb/sth)', '{"example":"This city features historic buildings","example_translation":"这座城市以历史建筑为特色"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('trait', '/treɪt/', '(某人性格中的)特性、特点；一点(c)', '{"example":"Her honesty is a valuable trait.","example_translation":"她的诚实是一种宝贵的特性。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('gender', '/ˈdʒendər/', '性(别)(n)', '{"example":"The form asks for your gender.","example_translation":"这张表格询问你的性别。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('sex', '/seks/', '(人、动、植物的)性(别)(u)', '{"example":"The doctor discussed the patient''''s sex.","example_translation":"医生讨论了患者的性别。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('age', '/eɪdʒ/', '年龄(段)(n)；时代、时期(c)', '{"example":"She reached the age of 18 last year.","example_translation":"她去年年满18岁。\n\n---\n\n例句: We live in the digital age now.\n翻译: 我们现在生活在数字时代。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('accent', '/ˈæksent/', '口音(n)；重音(c)；着重点(sing)；强调(vt)', '{"example":"She has a British accent.","example_translation":"她有一口英国口音。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('tone', '/toʊn/', '语气(c)；音调；色调(n)；(活动)基调(u, sing)；给…定调子(vt)', '{"example":"She changed her tone suddenly.","example_translation":"她突然改变了语气。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('voice', '/vɔɪs/', '(说话等的)声音、嗓音(n)；意见(c)；发言权(u, sing)；表达(vt)', '{"example":"She raised her voice in the meeting.","example_translation":"她在会议上提高了嗓门。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('mind', '/maɪnd/', '心、头脑(n)；心思；记忆力(c)；介意(~ doing)；注意、当心(v)', '{"example":"She minds her mind when reading.","example_translation":"她阅读时留意自己的心思。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('soul', '/soʊl/', '灵魂、心灵(c)；精神、精髓(u)', '{"example":"Her soul feels peaceful now.","example_translation":"她的心灵此刻感到平静。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('spirit', '/ˈspɪrɪt/', '精神、心灵(n)；情绪(pl)', '{"example":"Her spirit lifts when friends visit.","example_translation":"朋友来访时她情绪高涨。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('conscience', '/ˈkɑːnʃəns/', '良心；愧疚(n)', '{"example":"He had a clear conscience about the decision.","example_translation":"对这个决定他问心无愧。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('ego', '/ˈiːɡoʊ/', '自我；自负、自自尊心(c)(pl, egos)', '{"example":"He has a fragile ego and needs encouragement.","example_translation":"他自尊心脆弱，需要鼓励。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('beauty', '/ˈbjuːti/', '美、美丽(u)；美人、美好的物(c)', '{"example":"She is known for her beauty and grace.","example_translation":"她以美丽和优雅著称。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('grace', '/ɡreɪs/', '(动作的)优雅、优美；(上帝的)恩典(u)；使(某地或某物)优美(vt)', '{"example":"She moved with grace and elegance.","example_translation":"她举止优雅得体。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('health', '/helθ/', '健康(状况)；医疗保健(u)', '{"example":"Health is more important than wealth.","example_translation":"健康比财富更重要。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('fatigue', '/fəˈtiːɡ/', '疲劳(u)；(使…)疲劳(v)；疲劳的', '{"example":"The long journey left them in a state of fatigue.","example_translation":"长途旅行使他们疲惫不堪。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('hunger', '/ˈhʌŋɡər/', '饿；饥饿感(u)；渴望(sing)；渴望(phr v, ~ for/after sb/sth)', '{"example":"His hunger for knowledge led him to read widely.","example_translation":"他对知识的渴望使他广泛阅读。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('thirst', '/θɜːrst/', '口渴(u, sing)；干渴的状态(u)；渴望(sing, phr v, ~ for/after sth)', '{"example":"His thirst for adventure led him to travel.","example_translation":"他对冒险的渴望促使他去旅行。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('virtue', '/ˈvɜːrtʃuː/', '(某人具有的)美德、德行(c)；优点(n)；贞操(u)', '{"example":"Patience is a virtue.","example_translation":"耐心是一种美德。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('allegiance', '/əˈliːdʒəns/', '(对领袖、宗教等的)效忠、忠诚(n)', '{"example":"He swore allegiance to his country.","example_translation":"他宣誓效忠他的国家。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('charity', '/ˈtʃærəti/', '慈善、宽厚(u)；慈善事业(或团体)(n)', '{"example":"She donated money to charity.","example_translation":"她向慈善机构捐了钱。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('courtesy', '/ˈkɜːrtəsi/', '礼貌；好意(u)；礼貌的语言(或行为)(c)', '{"example":"She showed courtesy by holding the door.","example_translation":"她礼貌地为别人扶住了门。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('dignity', '/ˈdɪɡnəti/', '尊严、端庄；高贵(u)', '{"example":"She handled the situation with dignity.","example_translation":"她体面地处理了那个局面。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('discretion', '/dɪˈskreʃn/', '谨慎、慎重；自行决断权(u)', '{"example":"Use your discretion when sharing information.","example_translation":"分享信息时请自行斟酌。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('earnest', '/ˈɜːrnɪst/', '认真、诚挚；定金(u)；保证(c)；非常认真的、真诚的', '{"example":"He spoke in earnest about his plans.","example_translation":"他认真地说出了他的计划。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('effort', '/ˈefərt/', '努力(u)；成就、努力的结果(c)', '{"example":"Success requires effort and dedication.","example_translation":"成功需要努力和奉献。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('endeavor', '/ɪnˈdevər/', '(尤指新的或艰苦的)努力、尽力(n)；尽力(vi, ~ to do sth)(BrE, endeavour)', '{"example":"We will endeavor to meet your expectations.","example_translation":"我们会努力达到你的期望。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('humor', '/ˈhjuːmər/', '幽默(感)、诙谐(u)；心情(n)(BrE, humour)', '{"example":"He has a good sense of humor.","example_translation":"他很有幽默感。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('wit', '/wɪt/', '机智、风趣(u, sing)；智力(pl)', '{"example":"It takes wit to solve this puzzle.","example_translation":"解开这个谜题需要智慧。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('restraint', '/rɪˈstreɪnt/', '克制、抑制(u)；约束(措施)(n)', '{"example":"She showed restraint in her response.","example_translation":"她在回应中表现得很克制。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('thrift', '/θrɪft/', '节俭、节约(u)', '{"example":"Thrift is a virtue in difficult times.","example_translation":"节俭在困难时期是一种美德。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('hypocrisy', '/hɪˈpɑːkrəsi/', '伪善、虚伪(n)', '{"example":"His hypocrisy was exposed by his actions.","example_translation":"他的伪善被他的行为暴露了。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('vanity', '/ˈvænəti/', '自负、虚荣(心)(u)', '{"example":"Her vanity prevented her from accepting help.","example_translation":"她的虚荣心使她不愿接受帮助。"}');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('consider', '/kənˈsɪdər/', '仔细考虑（~ n/doing/wh-）；考虑、顾及（v）；认为（vt, ~ that | ~ sb/sth as sth）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('contemplate', '/ˈkɑːntəmpleɪt/', '沉思（v）；注视（vt）；打算（vt, ~ n/doing-/wh）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('meditate', '/ˈmedɪteɪt/', '冥想、沉思（vi, ~ on/upon）；考虑、计划（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('ponder', '/ˈpɑːndər/', '考虑、沉思（v, ~ on/over/about sth）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('think', '/θɪŋk/', '想、思考（~ about）；认为（~ that）；猜想（~ n/that/wh-）（v）；预料（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('analyze', '/ˈænəlaɪz/', '（为理解或解释而）分析、细察（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('deduce', '/dɪˈduːs/', '推断、演绎（vt, ~ that | ~ sth from sth）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('infer', '/ɪnˈfɜːr/', '推断、推理（vt, ~ n/that | ~ sth from sth）；做出推论（vi）；暗示（vt, ~ that）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('learn', '/lɜːrn/', '学、学习、学会；得知；意识到、吸取教训（~ that/from）（v）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('study', '/ˈstʌdi/', '学习（u）；（专题）研究；书房（c）；学习；研究（计划、文件、问题）；（为…）尽力（v）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('preview', '/ˈpriːvjuː/', '预习；预先审查（vt. c）；预告；预映、预展（c）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('review', '/rɪˈvjuː/', '（尤指为考试而）复习；回顾（vt. c）；评审、检讨（vt. n）；给（书、电影）写评论（vt）；评论（c）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('repeat', '/rɪˈpiːt/', '重复、重说、重写（v）；重做（vt）；重复的事物（c）；重复的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('know', '/noʊ/', '知道（v, ~ n/that/wh- | ~ of/about sth）；了解、认识（人或事物）（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('comprehend', '/ˌkɑːmprɪˈhend/', '领悟、充分理解（复杂困难的事物）（v）；包括（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('understand', '/ˌʌndərˈstænd/', '理解、明白；体谅；听说、得知；了解、认识到（原因等）（v）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('recollect', '/ˌrekəˈlekt/', '记起、回忆起（v, ~ that/speech | ~ sth/doing sth）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('remember', '/rɪˈmembər/', '记得（做某事，过去的人、事等）；回忆起（v）；（在祈祷时）缅怀（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('forget', '/fərˈɡet/', '忘记（~ n/that/wh- | ~ about sth | ~ to do sth）；忽略、不再想（v）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('envisage', '/ɪnˈvɪzɪdʒ/', '想象、设想（~ n/that/doing）；面对（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('imagine', '/ɪˈmædʒɪn/', '想象、设想（~ n/doing/that/wh-）；认为、料想（v）；猜想（vt, ~ that）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('anticipate', '/ænˈtɪsɪpeɪt/', '预期、预料（vt, ~ that/doing）；预言（vi）；提前使用（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('forecast', '/ˈfɔːrkæst/', '预测、预报（vt, ~ that/wh-. c）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('predict', '/prɪˈdɪkt/', '预测、预言、预报（vt, ~ n/that/wh-）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('guess', '/ɡes/', '猜测、推测（v, ~ n/that/wh- | ~ at. c, ~ at/about sth）；猜中（v）；想、以为（v, ~ that）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('assume', '/əˈsuːm/', '假定、假设；承担、就（职）；假装（…的样子等）（~ a manner of）（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('presume', '/prɪˈzuːm/', '推测、料想、（不肯定地）认为（vt）；利用（phr v, ~ on/upon sb/sth）；越权行事（vi）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('speculate', '/ˈspekjuleɪt/', '推测（v, ~ that/wh- | ~ on/about sth）；投机、做投机买卖（vi, ~ on/in sth）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('wonder', '/ˈwʌndər/', '琢磨、想知道、对…表示怀疑（v, ~ wh/speech- | ~ about）；奇迹、奇观（c）；惊奇、惊讶（u）；奇妙的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('calculate', '/ˈkælkjuleɪt/', '计算（~ n/that/wh-）；估计、预测（~ that/wh-）（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('compute', '/kəmˈpjuːt/', '计算、估算（结果、答案、总数等）（v）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('count', '/kaʊnt/', '计算、清点…的数（v, ~ sth up）；按顺序数数（vi, ~ from sth to/up to sth）；依赖、指望（phr v, ~ on sb/sth）；计数、点数；总数（c）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('add', '/æd/', '加（v, ~ A and/to B）；增加、添加（~ sth to sth）；补充说（~ that/speech）（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('deduct', '/dɪˈdʌkt/', '扣除、减去（~ sth from sth）；演绎、推理（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('subtract', '/səbˈtrækt/', '减去、减掉（vt, ~ sth from sth）；减少（vi）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('multiply', '/ˈmʌltɪplaɪ/', '乘、乘以（eg: ~ 2 and 3）；（使…）迅速增加；（使…）繁殖（v）；多样地、多重地', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('assess', '/əˈses/', '评估、估算（数量）（vt, ~ sth at sth）；评定（人、情况等）（vt, ~ sb/sth as sth）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('estimate', '/ˈestɪmət/', '估计、估算（vt, ~ sth at sth）；（对数量、成本等的）估计；估价（c）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('evaluate', '/ɪˈvæljueɪt/', '评估、评价（vt）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('weigh', '/weɪ/', '权衡（~ sth~up | ~ sth against sth）；称…的重量（vt）；重量是（lk v）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('audit', '/ˈɔːdɪt/', '审计、稽核；旁听（大学课程）（vt）；审计、稽核；（质量等的）检查（n）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('sum', '/sʌm/', '总结、概括（phr v, ~ sth~up）；总计（v）；金额；总数；算术（c）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('absent', '/ˈæbsənt/', '缺席的、不在的（~ from sth）；缺乏的（~ from sth）；心不在焉；缺席（vt, ~ yourself from sth）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('likely', '/ˈlaɪkli/', '可能的、有希望的（~ that | ~ to do sth）；大概、很可能（adv, most/very ~）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('possible', '/ˈpɑːsəbl/', '可能的；合理的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('potential', '/pəˈtenʃl/', '潜在的、可能的（only before noun）；潜力（u）；可能性（u, ~ for sth）；电势、电压（n）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('probable', '/ˈprɑːbəbl/', '很可能的；很可能的事（或物、情况）；很可能入选、获胜的人（或物）（c）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('latent', '/ˈleɪtnt/', '潜在的、潜伏的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('actual', '/ˈæktʃuəl/', '实际的、事实上的（only before noun）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('authentic', '/ɔːˈθentɪk/', '真实的、真正的；可靠的、可信的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('genuine', '/ˈdʒenjuɪn/', '真的、真正的；真诚的；真实的（情感、欲望等）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('real', '/ˈriːəl/', '真的；真正的、正宗的；真实的、实际存在的；很、非常', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('true', '/truː/', '真的、真实的；精确的；实质的；真实地', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('tangible', '/ˈtændʒəbl/', '有形的、实在的、确凿的；可触摸的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('transparent', '/trænsˈpærənt/', '（玻璃、塑料…）透明的；易识破的（谎言、借口…）；（语言、信息…）易懂的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('visible', '/ˈvɪzəbl/', '可见的；明显的、可察觉的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('apparent', '/əˈpærənt/', '明显的、明白易懂的；表面上的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('conspicuous', '/kənˈspɪkjuəs/', '显著的、显眼的、显而易见的；引人注目的（成功、勇气…）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('evident', '/ˈevɪdənt/', '明显的、清楚明白的（~ to sb | ~ in sth）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('obvious', '/ˈɑːbviəs/', '明显的、显然的（~ to sb）；自然而然的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('overt', '/oʊˈvɜːrt/', '（行动）公开的、明显的、公然的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('prominent', '/ˈprɑːmɪnənt/', '突出的、显著的；杰出的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('striking', '/ˈstraɪkɪŋ/', '显著的、吸引人的；俊秀的、妩媚动人的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('vivid', '/ˈvɪvɪd/', '生动的、栩栩如生的（记忆、描述…）；鲜艳的、耀眼的（颜色、光…）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('definite', '/ˈdefɪnət/', '明确的、清楚的（即容易看到、理解）；确定的、一定的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('explicit', '/ɪkˈsplɪsɪt/', '清楚明确的、直截了当的；清晰露骨的（描述性或暴力的语言或画面）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('intelligible', '/ɪnˈtelɪdʒəbl/', '清楚的、可理解的、明白易懂的（言语、文章或想法等）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('delicate', '/ˈdelɪkət/', '微妙的；精美的、纤细的；脆弱的；敏锐的；美味的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('subtle', '/ˈsʌtl/', '微妙的、不明显的；敏锐的、精细的；狡猾的；含蓄的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('ambiguous', '/æmˈbɪgjuəs/', '模棱两可的、含混不清的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('vague', '/veɪɡ/', '模糊的、不清楚的（印象、记忆…）；茫然的；不明确的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('opaque', '/oʊˈpeɪk/', '不透明的；难懂的、晦涩的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('o''clock', '/əˈklɑːk/', '…点钟（表示整点）（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('ago', '/əˈɡoʊ/', '以前（adv, eg: two years ~）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('past', '/pæst/', '过、晚于；经过（adv. prep）；过去的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('already', '/ɔːlˈredi/', '已经、早已（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('sometime', '/ˈsʌmtaɪm/', '在（过去或将来的）某时候（adv）；以前的（指某人曾经是）；偶尔（做某事）的（eg: ~ contributor）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('then', '/ðen/', '（指过去）当时、（指将来）届时；然后、接下来；那么、既然如此（adv）；当时（任职）的；那时（用于介词后）（u）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('hitherto', '/ˌhɪðərˈtuː/', '迄今、到目前为止（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('now', '/naʊ/', '现在、此刻、目前（adv）；既然（conj, also ~ that）；现在的、现任的；现在、此刻（u）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('nowadays', '/ˈnaʊədeɪz/', '现今、现在（与过去相比）（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('afterward', '/ˈæftərwərdz/', '以后、后来（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('henceforth', '/ˌhensˈfɔːrθ/', '今后、此后（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('later', '/ˈleɪtər/', '后来、以后（adv）；后来的、以后的；接近末期的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('thereafter', '/ˌðerˈæftər/', '之后、此后、其后（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('soon', '/suːn/', '很快、不久；早、快（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('again', '/əˈɡen/', '又一次、再一次；复原、返回原处（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('once', '/wʌns/', '一次；曾经（adv）；一旦（conj）；一次（u）；曾经的', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('twice', '/twaɪs/', '两次；两倍（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('ever', '/ˈevər/', '一直、永远；在任何时候（用于否定句、疑问句或与if连用的句子）；曾经；（用于when等后表示惊讶）究竟（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('forever', '/fərˈevər/', '永远、长久地（adv）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('meantime', '/ˈmiːntaɪm/', '与此同时（adv）；同时、其间（idm, in the ~）；暂时（idm, for the ~）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('meanwhile', '/ˈmiːnwaɪl/', '与此同时；其间（adv）；同时、期间（idm, in the ~）；暂时（idm, for the ~）', '');
INSERT INTO abcd (word, phonetic, translation, detail) VALUES ('over', '/ˈoʊvər/', '结束；完全覆盖；穿过；落下；多于（adv）；在…上面；遍及；在…期间（prep）', '');
